### ISSUE TITLE
FACS Tracking

### ISSUE THREAD

**Issue by kelshmo** [kelshmo/MMM#2]
- [x] John contacted 

- [x] Initial suggestions, John approved 

- [x] Finalize sample naming schema, assay - specific 

- [x] Create .csv and README, add to synapse with synapseID
