### ISSUE TITLE
ATACseq Tracking

### ISSUE THREAD

**Issue by kelshmo** [kelshmo/MMM#3]
- [x]  Contact Ling for completed metadata files (96 samples) 

- [x] Panos FACS should also be complete 

- [x] FACS tracking started for upcoming data capture with John
