### ISSUE TITLE
Proteomics Tracking

### ISSUE THREAD

**Issue by kelshmo** [kelshmo/MMM#5]
- [x] Contact Chang-Guy for tracking files (contacted Aug 28)

- [x] edit files, load to synapse 

- [x] get response from Chan-Gyu to finalize
